# Generated by Django 5.0.3 on 2024-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
