# Generated by Django 5.0.3 on 2024-04-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_can'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can',
        ),
    ]
