# Generated by Django 5.0.3 on 2024-04-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_can'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canv',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
