# Generated by Django 5.0.3 on 2024-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_canvas_canvas_data_canvas_last_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='canvas_data',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
