# Generated by Django 5.0.3 on 2024-04-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_canvas_canvas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='users',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
